### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by 7flash** [f0i/devcontainer-dfinity#1]
![image](https://user-images.githubusercontent.com/4569866/169949845-cfc3419d-a85c-4f44-80be-b7614a08f4d5.png)

**Comment by f0i** [comment]
Looks like [docker has a problem when the parent directory doesn't exist yet](https://stackoverflow.com/questions/66362660/docker-volume-mount-giving-root-ownership-of-parent-directory).

I updated the Docker image to create this folder with the correct permissions.
